#cloud-config

coreos:
  update:
    reboot-strategy: off
  etcd:
    discovery: http://%ETCD_DISCOVERY%:4001/v2/keys/cluster
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001

  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start
      runtime: no
      content: |
        [Unit]
        Description=fleet

        [Service]
        Environment=FLEET_PUBLIC_IP=$public_ipv4
        ExecStart=/usr/bin/fleet

    - name: rudder.service
      command: start
      content: |
        [Unit]
        Requires=etcd.service
        After=etcd.service

        [Service]
        ExecStartPre=-/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.100.0.0/16"}'
        ExecStart=/opt/bin/rudder -iface=$public_ipv4
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: docker.service
      command: restart
      content: |
        [Unit]
        Description=Docker Application Container Engine
        Documentation=http://docs.docker.io
        Requires=rudder.service
        After=rudder.service

        [Service]
        EnvironmentFile=/run/rudder/subnet.env
        ExecStartPre=-/usr/bin/ip link set dev docker0 down
        ExecStartPre=-/usr/sbin/brctl delbr docker0
        ExecStart=/usr/bin/docker -d -s=btrfs -H fd:// --bip=${RUDDER_SUBNET} --mtu=${RUDDER_MTU}
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: apiserver.service
      command: start
      content: |
        [Unit]
        After=etcd.service
        After=docker.service
        ConditionFileIsExecutable=/opt/bin/apiserver
        Description=Kubernetes API Server
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/apiserver \
        -address=0.0.0.0 \
        -port=8080 \
        -etcd_servers=http://127.0.0.1:4001 \
        -machines=%MINION_IP_ADDRS%
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: controller-manager.service
      command: start
      content: |
        [Unit]
        After=etcd.service
        After=docker.service
        ConditionFileIsExecutable=/opt/bin/controller-manager
        Description=Kubernetes Controller Manager
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/controller-manager -master=127.0.0.1:8080
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: scheduler.service
      command: start
      content: |
        [Unit]
        After=etcd.service
        After=docker.service
        ConditionFileIsExecutable=/opt/bin/scheduler
        Description=Kubernetes Scheduler
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/scheduler -master=127.0.0.1:8080
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        After=etcd.service
        After=docker.service
        ConditionFileIsExecutable=/opt/bin/kubelet
        Description=Kubernetes Kubelet
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/kubelet \
        -address=0.0.0.0 \
        -port=10250 \
        -hostname_override=$public_ipv4 \
        -etcd_servers=http://127.0.0.1:4001
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: proxy.service
      command: start
      content: |
        [Unit]
        After=etcd.service
        After=docker.service
        ConditionFileIsExecutable=/opt/bin/proxy
        Description=Kubernetes Proxy
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/proxy -etcd_servers=http://127.0.0.1:4001
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
